# Generated by Django 6.0.6 on 2026-06-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0002_goals'),
    ]

    operations = [
        migrations.AddField(
            model_name='goals',
            name='food',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='goals',
            name='sleep',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='goals',
            name='steps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goals',
            name='stress',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='stats',
            name='food',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='sleep',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='steps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='stress',
            field=models.IntegerField(default=-1),
        ),
    ]
