# Generated by Django 6.0.5 on 2026-06-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('statistics', '0002_goals'),
    ]

    operations = [
        migrations.AddField(
            model_name='goals',
            name='steps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='steps',
            field=models.IntegerField(default=0),
        ),
    ]
