# Generated by Django 6.0.5 on 2026-06-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('statistics', '0003_goals_steps_stats_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='goals',
            name='stress',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='stats',
            name='stress',
            field=models.IntegerField(default=-1),
        ),
    ]
