# Generated by Django 6.0.6 on 2026-06-17 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0003_goals_food_goals_sleep_stats_food_stats_sleep'),
        ('statistics', '0003_goals_steps_stats_steps'),
    ]

    operations = [
    ]
