# Generated by Django 6.0.5 on 2026-06-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='settings',
            field=models.TextField(default=''),
        ),
    ]
