name: Check code formatting
on:
  pull_request:
    branches: [main, dev]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - name: Prettify code
        uses: creyD/prettier_action@v4.6
        with:
          prettier_options: "-c **/*.{ts,tsx}"
          working_directory: '${{ github.action_path }}/client'
          dry: True

